# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5aa4c7746bbcf18b8fb7d00000b47938b0271ea4741e289f20ce7037c752b8a9f50ef1873c61317a15fba1fe842cda1eb61c20391a64a14df5c2155dde90d4bb

test:
  secret_key_base: 7db917f47d4759404324b90e05d1376d6ad3a548fdf07c34d47fd0e9c53352be0a3ee32ade91da82f229d3013fa52641c8b4adf74c2265c8553b58f2ad818d3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
